### ISSUE TITLE
Issues in the submitted 2.4.11 package and multiple older revisions

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/doctest#5]
This is just a note that I won't be propagating from queue to public the revisions you have submitted (2.4.10+1, etc) along with the 2.4.11 package (2.4.11 I will propagate).

The reason for this is that the changes are just too extensive and therefore risky for a revision (which will be replacing the previous version). You have essentially rewrote the build of the package from scratch (including adding a large number of new configuration variables) and its hard for me to reason whether it is strictly backwards compatible with the previous version (which a revision must be).

Sorry for all the extra work that you had put into this (though these revisions will still be available in the git repository if someone needs them and cannot just switch to 2.4.11 for some reason). FWIW, I am discussing this topic in the packaging guide which is almost ready.

**Comment by lyrahgames** [comment]
> Sorry for all the extra work that you had put into this (though these revisions will still be available in the git repository if someone needs them and cannot just switch to 2.4.11 for some reason). FWIW, I am discussing this topic in the packaging guide which is almost ready.

Ok then thanks for the notice and for propagating `2.4.11`. I wasn't aware that I would need to keep it strictly backwards compatible for older versions. And yeah, at least it will now be discussed in the packaging guide.

Still, lot of CI runs of the older versions are constantly sending me mails due to compilation failure and the `manifest` value `build-warning-email` that quickly evolved into noise. I would really much like to stop CI runs from doing that for these older packages.

**Comment by boris-kolpackov** [comment]
> Still, lot of CI runs of the older versions are constantly sending me mails due to compilation failure and the `manifest` value `build-warning-email` that quickly evolved into noise. I would really much like to stop CI runs from doing that for these older packages.

Yes, this feature turned more trouble than it's worth. We are going to change the current behavior to only send such notifications for the latest version. So you should see some relief in a couple of days.

**Comment by lyrahgames** [comment]
Thank you! I am glad to hear this.
I close the issue as you have already propagated version `2.4.11`. Feel free to re-open it.

**Comment by boris-kolpackov** [comment]
@lyrahgames We've made the email notification change on cppget.org today. Please let me know if you still get email about older versions from now on.

**Comment by lyrahgames** [comment]
@boris-kolpackov Thank you very much for the change. I have tracked my mails over the last three weeks and wanted to inform you that I didn't get any new error/warning mails from older versions.
